# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layers_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(566, 555)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        #palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        #palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 212, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 85))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 85, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        #palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.list = QtWidgets.QComboBox(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(190, 50, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.list.setFont(font)
        self.list.setObjectName("list")
        self.checkIsInput = QtWidgets.QCheckBox(self.centralwidget)
        self.checkIsInput.setGeometry(QtCore.QRect(150, 100, 21, 17))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.checkIsInput.setFont(font)
        self.checkIsInput.setText("")
        self.checkIsInput.setObjectName("checkIsInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 100, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 140, 511, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.inputShape = QtWidgets.QLineEdit(self.centralwidget)
        self.inputShape.setGeometry(QtCore.QRect(410, 100, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.inputShape.setFont(font)
        self.inputShape.setObjectName("inputShape")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 170, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setGeometry(QtCore.QRect(320, 512, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setGeometry(QtCore.QRect(440, 512, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.closeButton.setFont(font)
        self.closeButton.setObjectName("closeButton")
        self.par1_label = QtWidgets.QLabel(self.centralwidget)
        self.par1_label.setGeometry(QtCore.QRect(15, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par1_label.setFont(font)
        self.par1_label.setObjectName("par1_label")
        self.par5_label = QtWidgets.QLabel(self.centralwidget)
        self.par5_label.setGeometry(QtCore.QRect(15, 260, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par5_label.setFont(font)
        self.par5_label.setObjectName("par5_label")
        self.par3_label = QtWidgets.QLabel(self.centralwidget)
        self.par3_label.setGeometry(QtCore.QRect(15, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par3_label.setFont(font)
        self.par3_label.setObjectName("par3_label")
        self.par7_label = QtWidgets.QLabel(self.centralwidget)
        self.par7_label.setGeometry(QtCore.QRect(15, 290, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par7_label.setFont(font)
        self.par7_label.setObjectName("par7_label")
        self.par11_label = QtWidgets.QLabel(self.centralwidget)
        self.par11_label.setGeometry(QtCore.QRect(15, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par11_label.setFont(font)
        self.par11_label.setObjectName("par11_label")
        self.par9_label = QtWidgets.QLabel(self.centralwidget)
        self.par9_label.setGeometry(QtCore.QRect(15, 320, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par9_label.setFont(font)
        self.par9_label.setObjectName("par9_label")
        self.par13_label = QtWidgets.QLabel(self.centralwidget)
        self.par13_label.setGeometry(QtCore.QRect(15, 380, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par13_label.setFont(font)
        self.par13_label.setObjectName("par13_label")
        self.par15_label = QtWidgets.QLabel(self.centralwidget)
        self.par15_label.setGeometry(QtCore.QRect(15, 410, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par15_label.setFont(font)
        self.par15_label.setObjectName("par15_label")
        self.par17_label = QtWidgets.QLabel(self.centralwidget)
        self.par17_label.setGeometry(QtCore.QRect(15, 440, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par17_label.setFont(font)
        self.par17_label.setObjectName("par17_label")
        self.par8_label = QtWidgets.QLabel(self.centralwidget)
        self.par8_label.setGeometry(QtCore.QRect(290, 290, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par8_label.setFont(font)
        self.par8_label.setObjectName("par8_label")
        self.par4_label = QtWidgets.QLabel(self.centralwidget)
        self.par4_label.setGeometry(QtCore.QRect(290, 230, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par4_label.setFont(font)
        self.par4_label.setObjectName("par4_label")
        self.par2_label = QtWidgets.QLabel(self.centralwidget)
        self.par2_label.setGeometry(QtCore.QRect(290, 200, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par2_label.setFont(font)
        self.par2_label.setObjectName("par2_label")
        self.par19_label = QtWidgets.QLabel(self.centralwidget)
        self.par19_label.setGeometry(QtCore.QRect(120, 480, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par19_label.setFont(font)
        self.par19_label.setObjectName("par19_label")
        self.par18_label = QtWidgets.QLabel(self.centralwidget)
        self.par18_label.setGeometry(QtCore.QRect(290, 440, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par18_label.setFont(font)
        self.par18_label.setObjectName("par18_label")
        self.par16_label = QtWidgets.QLabel(self.centralwidget)
        self.par16_label.setGeometry(QtCore.QRect(290, 410, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par16_label.setFont(font)
        self.par16_label.setObjectName("par16_label")
        self.par14_label = QtWidgets.QLabel(self.centralwidget)
        self.par14_label.setGeometry(QtCore.QRect(290, 380, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par14_label.setFont(font)
        self.par14_label.setObjectName("par14_label")
        self.par12_label = QtWidgets.QLabel(self.centralwidget)
        self.par12_label.setGeometry(QtCore.QRect(290, 350, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par12_label.setFont(font)
        self.par12_label.setObjectName("par12_label")
        self.par10_label = QtWidgets.QLabel(self.centralwidget)
        self.par10_label.setGeometry(QtCore.QRect(290, 320, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par10_label.setFont(font)
        self.par10_label.setObjectName("par10_label")
        self.par6_label = QtWidgets.QLabel(self.centralwidget)
        self.par6_label.setGeometry(QtCore.QRect(290, 260, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par6_label.setFont(font)
        self.par6_label.setObjectName("par6_label")
        self.par1 = QtWidgets.QLineEdit(self.centralwidget)
        self.par1.setGeometry(QtCore.QRect(150, 200, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par1.setFont(font)
        self.par1.setObjectName("par1")
        self.par5 = QtWidgets.QLineEdit(self.centralwidget)
        self.par5.setGeometry(QtCore.QRect(150, 260, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par5.setFont(font)
        self.par5.setObjectName("par5")
        self.par3 = QtWidgets.QLineEdit(self.centralwidget)
        self.par3.setGeometry(QtCore.QRect(150, 230, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par3.setFont(font)
        self.par3.setObjectName("par3")
        self.par7 = QtWidgets.QLineEdit(self.centralwidget)
        self.par7.setGeometry(QtCore.QRect(150, 290, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par7.setFont(font)
        self.par7.setObjectName("par7")
        self.par16 = QtWidgets.QLineEdit(self.centralwidget)
        self.par16.setGeometry(QtCore.QRect(425, 410, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par16.setFont(font)
        self.par16.setObjectName("par16")
        self.par14 = QtWidgets.QLineEdit(self.centralwidget)
        self.par14.setGeometry(QtCore.QRect(425, 380, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par14.setFont(font)
        self.par14.setObjectName("par14")
        self.par12 = QtWidgets.QLineEdit(self.centralwidget)
        self.par12.setGeometry(QtCore.QRect(425, 350, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par12.setFont(font)
        self.par12.setObjectName("par12")
        self.par10 = QtWidgets.QLineEdit(self.centralwidget)
        self.par10.setGeometry(QtCore.QRect(425, 320, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par10.setFont(font)
        self.par10.setObjectName("par10")
        self.par8 = QtWidgets.QLineEdit(self.centralwidget)
        self.par8.setGeometry(QtCore.QRect(425, 290, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par8.setFont(font)
        self.par8.setObjectName("par8")
        self.par6 = QtWidgets.QLineEdit(self.centralwidget)
        self.par6.setGeometry(QtCore.QRect(425, 260, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par6.setFont(font)
        self.par6.setObjectName("par6")
        self.par4 = QtWidgets.QLineEdit(self.centralwidget)
        self.par4.setGeometry(QtCore.QRect(425, 230, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par4.setFont(font)
        self.par4.setObjectName("par4")
        self.par2 = QtWidgets.QLineEdit(self.centralwidget)
        self.par2.setGeometry(QtCore.QRect(425, 200, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par2.setFont(font)
        self.par2.setObjectName("par2")
        self.par17 = QtWidgets.QLineEdit(self.centralwidget)
        self.par17.setGeometry(QtCore.QRect(150, 440, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par17.setFont(font)
        self.par17.setObjectName("par17")
        self.par15 = QtWidgets.QLineEdit(self.centralwidget)
        self.par15.setGeometry(QtCore.QRect(150, 410, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par15.setFont(font)
        self.par15.setObjectName("par15")
        self.par13 = QtWidgets.QLineEdit(self.centralwidget)
        self.par13.setGeometry(QtCore.QRect(150, 380, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par13.setFont(font)
        self.par13.setObjectName("par13")
        self.par11 = QtWidgets.QLineEdit(self.centralwidget)
        self.par11.setGeometry(QtCore.QRect(150, 350, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par11.setFont(font)
        self.par11.setObjectName("par11")
        self.par9 = QtWidgets.QLineEdit(self.centralwidget)
        self.par9.setGeometry(QtCore.QRect(150, 320, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par9.setFont(font)
        self.par9.setObjectName("par9")
        self.par19 = QtWidgets.QLineEdit(self.centralwidget)
        self.par19.setGeometry(QtCore.QRect(270, 480, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par19.setFont(font)
        self.par19.setObjectName("par19")
        self.par18 = QtWidgets.QLineEdit(self.centralwidget)
        self.par18.setGeometry(QtCore.QRect(425, 440, 113, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.par18.setFont(font)
        self.par18.setObjectName("par18")
        self.boolcheck1 = QtWidgets.QCheckBox(self.centralwidget)
        self.boolcheck1.setGeometry(QtCore.QRect(200, 202, 21, 17))
        self.boolcheck1.setText("")
        self.boolcheck1.setObjectName("boolcheck1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Добавить слой"))
        self.label_2.setText(_translate("MainWindow", "Входной слой"))
        self.label_3.setText(_translate("MainWindow", "Входная форма"))
        self.label_4.setText(_translate("MainWindow", "Параметры слоя"))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
        self.closeButton.setText(_translate("MainWindow", "Отмена"))
        self.par1_label.setText(_translate("MainWindow", "Входной слой"))
        self.par5_label.setText(_translate("MainWindow", "Входной слой"))
        self.par3_label.setText(_translate("MainWindow", "Входной слой"))
        self.par7_label.setText(_translate("MainWindow", "Входной слой"))
        self.par11_label.setText(_translate("MainWindow", "Входной слой"))
        self.par9_label.setText(_translate("MainWindow", "Входной слой"))
        self.par13_label.setText(_translate("MainWindow", "Входной слой"))
        self.par15_label.setText(_translate("MainWindow", "Входной слой"))
        self.par17_label.setText(_translate("MainWindow", "Входной слой"))
        self.par8_label.setText(_translate("MainWindow", "Входной слой"))
        self.par4_label.setText(_translate("MainWindow", "Входной слой"))
        self.par2_label.setText(_translate("MainWindow", "Входной слой"))
        self.par19_label.setText(_translate("MainWindow", "Входной слой"))
        self.par18_label.setText(_translate("MainWindow", "Входной слой"))
        self.par16_label.setText(_translate("MainWindow", "Входной слой"))
        self.par14_label.setText(_translate("MainWindow", "Входной слой"))
        self.par12_label.setText(_translate("MainWindow", "Входной слой"))
        self.par10_label.setText(_translate("MainWindow", "Входной слой"))
        self.par6_label.setText(_translate("MainWindow", "Входной слой"))

